config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :products
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  # money-rails gem
  monetize :price_cents
  monetize :shipping_price_cents

  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def index
    @products = Product.order(:title)
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params)
    
    if @product.save
      redirect_to edit_admin_product_path(@product), notice: 'The product was created successfully.'
    else
      flash[:error] = 'There was an error creating the product.'
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end
  
private
 
  def product_params
    params.require(:product).permit(:title, :description, :price, :shipping_price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :shipping_price %>
  <%= f.submit %>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Edit Product</h1>
<%= render 'form' %>

app/views/admin/products/index.html.erb
<h1>Products</h1>
 
<p><%= link_to 'New Product', new_admin_product_path %></p>
 
<% if @products.any? %>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Shipping</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.title %></td>
          <td><%= number_to_currency product.price %></td>
          <td><%= number_to_currency product.shipping_price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/admin/products/new.html.erb
<h1>New Product</h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntroToFeatureSpecs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, message| %>
  <div id="flash-<%= key %>" class="flash-<%= key %>">
    <%= message %>
  </div>
<% end %>

<%= yield %>

</body>
</html>